version: 2
updates:
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: daily
    time: "10:00"
  open-pull-requests-limit: 10
  reviewers:
  - jubairsaidi
  ignore:
  - dependency-name: "@types/node"
    versions:
    - 14.14.22
    - 14.14.25
    - 14.14.27
    - 14.14.28
    - 14.14.30
    - 14.14.31
    - 14.14.32
    - 14.14.33
    - 14.14.34
    - 14.14.35
    - 14.14.36
    - 14.14.37
    - 14.14.39
    - 14.14.41
    - 15.0.0
  - dependency-name: dependency-cruiser
    versions:
    - 9.22.0
    - 9.23.0
    - 9.23.1
    - 9.23.2
    - 9.23.3
    - 9.24.0
    - 9.25.0
    - 9.25.1
  - dependency-name: "@types/eslint"
    versions:
    - 7.2.6
    - 7.2.7
    - 7.2.8
    - 7.2.9
  - dependency-name: y18n
    versions:
    - 4.0.1
    - 4.0.2
  - dependency-name: "@types/chai"
    versions:
    - 4.2.14
    - 4.2.15
    - 4.2.16
  - dependency-name: "@types/jest"
    versions:
    - 26.0.20
    - 26.0.21
    - 26.0.22
  - dependency-name: "@types/prettier"
    versions:
    - 2.1.6
    - 2.2.0
    - 2.2.1
    - 2.2.2
  - dependency-name: eslint-plugin-prettier
    versions:
    - 3.3.1
