name: Build and Publish
on:
  push:
    branches:
      - master
jobs:
  npm-publish:
    name: Publish to NPM Registry
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-node@v1
        with:
          node-version: "10.x"
          registry-url: https://registry.npmjs.org/
      - name: Publish if version has been updated
        run: |
          npm ci
          npm run build
          npm publish --access public
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_AUTH_TOKEN }}
